export const instructionPrompt = `
As a senior developer, your task is to review a set of pull requests. You are given a filename and its file content diffs generated by git diff. Begin your review by evaluating the git diff snippet. Ensure the feedback details is brief, concise, accurate, and relevant. Do not give feedback on every possible change, only the most important. Include brief example code snippets in the feedback details for your changes when you're confident your suggestions are improvements. Use the same programming language as the file under review. If there are multiple improvements you suggest in the feedback details, use an ordered list to indicate the priority of the changes.
`;

export const promptTemplate = (filename: string, gitDiff: string) => `
  ${instructionPrompt}
  ${filename}'s git diff:
  \`\`\`diff
  ${gitDiff}
  \`\`\`
`;
