name: Code Review Private AI CI

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install code-review-private-ai
        run: npm install code-review-private-ai

      - name: Run code review script
        run: npx code-review-private-ai review --model="llama-2-7b-chat.ggmlv3.q4_0.bin" --temperature="0.1" --basePath="http://localhost:8000/v1"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_SHA: ${{ github.sha }}
